; this section loops over a string and displays it
drawIntro
		ldx #$0
		ldy #$0
introLoop	lda message,y        ; put the msg + x offset in accumulator
		and #$3f             ; strip the top two bytes away
		sta $0400,x          ; put the string byte into the screen + offset
		sta $0500,x
		sta $0600,x
		sta $0700,x
		inx                  ; increment x
		iny
		tya
		and #$0f
		tay
		cpx #255             ; see if x != the length of the string
		bne introLoop
		rts

; clear the whole screen first
clear_screen 	pha	; save registers
			tya
			pha
			txa
			pha

			ldx #$0
			lda #$20
cs1			sta $0400,x
			sta $0500,x
			sta $0600,x
			sta $0700,x
			inx
			cpx #0
			bne cs1

			pla	; restore registers
			tax
			pla
			tay
			pla

			rts

setup_vblank
	sei        ;disable maskable IRQs
	pha		 ; store the acc
	lda #$7f
	sta $dc0d  ;disable timer interrupts which can be generated by the two CIA chips
	sta $dd0d  ;the kernal uses such an interrupt to flash the cursor and scan the keyboard, so we better
	           ;stop it.

	lda $dc0d  ;by reading this two registers we negate any pending CIA irqs.
	lda $dd0d  ;if we don't do this, a pending CIA irq might occur after we finish setting up our irq.
	           ;we don't want that to happen.

	lda #$01   ;this is how to tell the VICII to generate a raster interrupt
	sta $d01a

	lda #$40   ;this is how to tell at which rasterline we want the irq to be triggered
	sta $d012

	lda #$1b   ;as there are more than 256 rasterlines, the topmost bit of $d011 serves as
	sta $d011  ;the 9th bit for the rasterline we want our irq to be triggered.
	           ;here we simply set up a character screen, leaving the topmost bit 0.

	lda #$35   ;we turn off the BASIC and KERNAL rom here
	sta $01    ;the cpu now sees RAM everywhere except at $d000-$e000, where still the registers of
	           ;SID/VICII/etc are visible

	lda #<irq  ;this is how we set up
	sta $fffe  ;the address of our interrupt code
	lda #>irq
	sta $ffff

	cli        ;enable maskable interrupts again

	pla 		 ; restore
	rts  ;we better don't RTS, the ROMS are now switched off, there's no way back to the system
